version: '3.3'
services:
  db:
    image: kartoza/postgis:14-3.1
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'robot_apocalypse'
    ports:
      - 5432:5432
    healthcheck:
      test: "exit 0"
    volumes:
      - postgis-data:/var/lib/postgresql

volumes:
  postgis-data: